### ISSUE TITLE
Questions about training data collection.

### ISSUE THREAD

**Issue by qorgh346** [ShunChengWu/SceneGraphFusion#11]
Hello! I'm going to apply the author's Scene Graph Fusion technology after collecting data in the AI2Thor environment. Currently, when I establish a relationship between two objects, I am working manually. Can you tell me how you collected the data?

**Comment by qorgh346** [comment]
답...

**Comment by ShunChengWu** [comment]
There are ways to do this. I didn't create the 3DSSG dataset. Base on my knowledge, the authors first use rule-based methods to do automatic labeling, then they relied on human labor to fix the wrong/missing one.

**Comment by qorgh346** [comment]
oh...Thank you!!
