### ISSUE TITLE
no imgui.h

### ISSUE THREAD

**Issue by Willforcv** [ShunChengWu/SceneGraphFusion#12]
fatal error: imgui.h: 没有那个文件或目录?  Has anyone encountered this problem?  thx

**Comment by Willforcv** [comment]
[ 83%] Linking CXX static library liblibGraphSLAM.a
[ 83%] Built target libGraphSLAM
[ 91%] Building CXX object app/GraphSLAM/CMakeFiles/exe_GraphSLAM.dir/main.cc.o
In file included from /home/will/work/SceneGraphFusion/libGraphSLAM/../lib/../libGUI3D/libGUI3D/GUI3D.h:3:0,
                 from /home/will/work/SceneGraphFusion/app/GraphSLAM/main.cc:19:
/home/will/work/SceneGraphFusion/libGraphSLAM/../lib/../libGUI3D/libGUI3D/../libGUI/GUI.h:2:10: fatal error: imgui.h: 没有那个文件或目录
 #include "imgui.h"
          ^~~~~~~~~
compilation terminated.
make[2]: *** [app/GraphSLAM/CMakeFiles/exe_GraphSLAM.dir/build.make:63：app/GraphSLAM/CMakeFiles/exe_GraphSLAM.dir/main.cc.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:209：app/GraphSLAM/CMakeFiles/exe_GraphSLAM.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2

**Comment by Willforcv** [comment]
Connect via proxy, and build ~

**Comment by BIT-TYJ** [comment]
hello,I met the same problem, I wonder what's the meaning of connecting via proxy, thank you !

**Comment by PericlesHat** [comment]
> hello,I met the same problem, I wonder what's the meaning of connecting via proxy, thank you !

I think this might help. #29

**Comment by dhxxoo** [comment]
> 

hi, i have the same problem. Did you solve it? Could you please tell me how to deal with it? Really appreciate it.

**Comment by BIT-TYJ** [comment]
> > 
> 
> hi, i have the same problem. Did you solve it? Could you please tell me how to deal with it? Really appreciate it.

this one may help,  https://github.com/ShunChengWu/SceneGraphFusion/issues/29#issue-1604672543

**Comment by dhxxoo** [comment]
> 

yeah, finally it works, thx.
