### ISSUE TITLE
Question1

### ISSUE THREAD

**Issue by qorgh346** [ShunChengWu/SceneGraphFusion#15]
![image](https://user-images.githubusercontent.com/77768280/151295758-561b8747-dfdb-4074-9034-a3041302ce62.png)

Hello
I'm analyzing the author's code.
I am sending you an issue because I have one question.

Predicate (node.first ---- (realization) ----- node.second)
Question 1.
Can you tell me what the code in the picture means?

**Comment by ShunChengWu** [comment]
can you create a permalink w.r.t. the lines directly in this repo?
It will be easier for me to locate the code you mentioned. 
e.g. 
https://github.com/ShunChengWu/SceneGraphFusion/blob/8c8b815c763c1aeaaf35858cf09cc2f8c401a76f/app/GraphSLAM/main.cc#L13-L19

just based on the snapshot, I think this is the check if a feature is computed at a certain level. Probably it's about the gnn feature

**Comment by qorgh346** [comment]
Thank you!!!!
