### ISSUE TITLE
Run on custom sequence

### ISSUE THREAD

**Issue by AKC141096** [ShunChengWu/SceneGraphFusion#17]
Hello,

Can you tell me briefly what changes to the code are required to run on a custom image sequence?

**Comment by ShunChengWu** [comment]
you can expand the dataloader lib by adding a new class with inheriting the abstract class.
https://github.com/ShunChengWu/SceneGraphFusion/tree/main/libDataLoader

**Comment by BIT-TYJ** [comment]
> Hello,
> 
> Can you tell me briefly what changes to the code are required to run on a custom image sequence?

Hello, could you please provide the code of dataloader to run on a custom image sequence?

**Comment by JoseAndresMR** [comment]
Hello, any news about running on a custom sequence? @BIT-TYJ @AKC141096  Thanks!
