### ISSUE TITLE
Reproducing Scannet Panoptic Segmentation Results

### ISSUE THREAD

**Issue by weders** [ShunChengWu/SceneGraphFusion#18]
Hi @ShunChengWu,

Thanks a lot for providing this awesome code base. It runs really nicely without a lot of effort. 

However, I have one question regarding evaluating results. I'd like to run the same evaluation (Panoptic Segmentation) as you show in Table 5 and 6 in the paper. What code part do I need to run if I want to do this on a very specific set of scenes? Ideally, I'd like to output it in the ScanNet format for both semantic and instance segmentation. I.e. having a semantic label for each label of the ground-truth mesh and a vertex mask for each predicted instance. 

Thank you very much!

**Comment by ShunChengWu** [comment]
We use the script provided by [ScanNet](https://github.com/ScanNet/ScanNet/tree/master/BenchmarkScripts/3d_evaluation) by outputting the per-point/vertex label with nearest neighbor search. 
As you may also notice that the evaluation script is for semantic instances, we add an option to unify the background (things) instances.

**Comment by ShunChengWu** [comment]
closed due to inactivity. feel free to reopen it.
