### ISSUE TITLE
Bugs Report and Fix

### ISSUE THREAD

**Issue by Kenneth-Wong** [ShunChengWu/SceneGraphFusion#2]
1. Bugs about **invoke_result**: ```build/include/eigen3/Eigen/src/Core/util/Meta.h:617:25: error: ‘invoke_result’ in namespace ‘std’ does not name a template type```

   - This is a bug caused by not compiling with c++17. However, although the CMAKE_CXX_STANDARD flag is 17 in the CMakeList.txt, the bug still exists. The probable solution is to comment these lines in the head files, e.g., when compiling, change the code from 

     ```c++
     #if EIGEN_HAS_STD_INVOKE_RESULT
     template<typename F, typename... ArgTypes>
     struct invoke_result {
        typedef typename std::invoke_result<F, ArgTypes...>::type type1;
        typedef typename remove_all<type1>::type type;
      };
      #elif EIGEN_HAS_CXX11
      template<typename F, typename... ArgTypes>
      struct invoke_result {
        typedef typename result_of<F(ArgTypes...)>::type type1;
        typedef typename remove_all<type1>::type type;
      };
      #else
      template<typename F, typename ArgType0 = void, typename ArgType1 = void, typename ArgType2 = void>
      struct invoke_result {
        typedef typename result_of<F(ArgType0, ArgType1, ArgType2)>::type type1;
        typedef typename remove_all<type1>::type type;
      };

     ```

     to

     ```c++
     /*#if EIGEN_HAS_STD_INVOKE_RESULT
     template<typename F, typename... ArgTypes>
     struct invoke_result {
        typedef typename std::invoke_result<F, ArgTypes...>::type type1;
        typedef typename remove_all<type1>::type type;
      };*/
      #if EIGEN_HAS_CXX11
      template<typename F, typename... ArgTypes>
      struct invoke_result {
        typedef typename result_of<F(ArgTypes...)>::type type1;
        typedef typename remove_all<type1>::type type;
      };
      #else
      template<typename F, typename ArgType0 = void, typename ArgType1 = void, typename ArgType2 = void>
      struct invoke_result {
        typedef typename result_of<F(ArgType0, ArgType1, ArgType2)>::type type1;
        typedef typename remove_all<type1>::type type;
      };

     ```

     You can do the same thing in other files when this bug emerges.

2. Bugs about **io**: ```SceneGraphFusion/libGraphSLAMGUI/../renderer/Scan3R_json_loader.h:9:18: error: ‘io’ in namespace ‘::’ does not name a type```

   - You just need to delete the "::io" in some related files. 

3. Bugs about **clamp**: ```SceneGraphFusion/libGraphSLAMGUI/graphDrawer/graph_drawer.cpp:81:23: error: ‘clamp’ is not a member of ‘std’```

   - This is also a bug caused by C++ standard. You can change the clamp function from:

     ```c++
     float scale = std::clamp((5-std::sqrt(point.z()))/5.f,0.1f,1.f);
     ```

     to

     ```c++
     float scale = (5-std::sqrt(point.z()))/5.f;
     if (scale < 0.1f)
     {
       scale = 0.1f;
     } 
     else if (scale > 1.f)
     {
       scale = 1.f;
     }
     ```

4. Bugs about **atomoic**: it  emerges in the https://github.com/ShunChengWu/SceneGraphFusion/blob/4c632d12dd492c362ee2708a85410f367724b572/libGraphSLAM/node.h#L52 and https://github.com/ShunChengWu/SceneGraphFusion/blob/4c632d12dd492c362ee2708a85410f367724b572/libGraphSLAM/node.h#L61. 

   - It may be also caused by c++17 standard. You can change them to 

     ```c++
     std::atomic_int instance_idx = {0};
     ```

     ```c++
     std::atomic_bool mbNeedUpdateNodeFeature = {false};
     ```

5. https://github.com/ShunChengWu/SceneGraphFusion/blob/4c632d12dd492c362ee2708a85410f367724b572/libGraphSLAM/node.cpp#L74

   - This line should be changed to ```std::unique_lock<std::mutex> lock_node(mMutNode);```

6. About **eigen**

   - If this bug emege, you may build and install the eigen3 from source.

7. Bugs about **freetype2** (I guess it may be caused by HarfBuzz), the error may emerge as: ```SceneGraphFusion/build/external/FreeType2/src/autofit/afscript.h:35:11: error: ‘HB_SCRIPT_ADLAM’ undeclared here (not in a function)``` and ```SceneGraphFusion/build/external/FreeType2/src/autofit/afscript.h:278:11: error: ‘HB_SCRIPT_OSAGE’ undeclared here (not in a function)```

   - The temporary solution is to find out the associated lines in these head files and comment them. Another head file is ```afstyle.h```.

8. When running the executable file, you should put the ```3RScan.json``` and ```objects.json```(from 3DSSG) under the correct directory. E.g., if the --pth_in is ```scans/sequence_idxxxx/sequence/```, you should put these two files under ```scans/```

9. It seems that the GUI does not support remote X forward, i.e., if you compile the project on a remote server and run it on the local computer, the error may emerge: ```Error: GLX: Forward compatibility requested but GLX_ARB_create_context_profile is unavailable```. Finally I compiled it on the local computer with an NVIDIA GPU.

**Comment by ShunChengWu** [comment]
Hey, thanks for the detailed report and suggestion. The code hasn't been tested under a different environment. We have only tested it within a docker environment but with the same setup. 
I will try to merge your suggestions into the code to make it easier to compile. 
Thanks
