### ISSUE TITLE
Using the GroundTruth depth image of dataset instead of the rendered view, result is not so good.

### ISSUE THREAD

**Issue by Zedzou** [ShunChengWu/SceneGraphFusion#22]
Hello, Thank you for your cool project. when I using the depth image of dataset instead of the rendered view, why its result is not so good. I just set the "renderer" to false on line 219 of the main.cc. So I want to consult What is the specific reason. Thank you very much.

**Comment by ShunChengWu** [comment]
First of all the provided model was trained with rendered depth image. The reason for training on the rendered images is that the semantic scene graph dataset (3RScan) we used to train our model has very poor depth maps. 
The front-end segmentation method segments a scene only base on the given depth map, and the corresponding projected geometry. It is quite sensitive to the input depth quality. This is adjustable by configuring the parameters in the *_config.h headers (https://github.com/ShunChengWu/SceneGraphFusion/tree/main/lib/inseg_lib). 

Our method can be trained with rendered depth maps and used with real depth maps, as long as the front-end segmentation method can provide a similar segmentation pattern. 
Please check our Humanoid [project](https://www.mec.ed.tum.de/am/forschung/abgeschlossene-projekte/humanoide-robotik/lola/) and the demo [video](https://www.youtube.com/watch?v=_lYvIhAQf1k).
