### ISSUE TITLE
Question about output of each frame RGB, Depth image

### ISSUE THREAD

**Issue by BIT-TYJ** [ShunChengWu/SceneGraphFusion#27]
Hello, it's a great work!
I want to know where is the output (i.e., nodes, edges, pointcloud after instance segmentation) of each pair of RGBD images?
I searched but don't get it.
Looking forward to your reply!

**Comment by ShunChengWu** [comment]
We do not compute SG per-frame.
the code only outputs the final fused scene graph. If you want to save intermediate results, you can implement it.
