### ISSUE TITLE
fatal error: imgui.h: No such file or directory

### ISSUE THREAD

**Issue by PericlesHat** [ShunChengWu/SceneGraphFusion#29]
Thanks for your great work. I got some problems in installation. When I ran `make` in the `./build` dir, it shows the missing header "imgui.h". Logs:

```
In file included from /home/xxx/3dssg/SceneGraphFusion/libGraphSLAM/../lib/../libGUI3D/libGUI3D/GUI3D.h:3:0,
                 from /home/xxx/3dssg/SceneGraphFusion/app/GraphSLAM/main.cc:19:
/home/xxx/3dssg/SceneGraphFusion/libGraphSLAM/../lib/../libGUI3D/libGUI3D/../libGUI/GUI.h:2:10: fatal error: imgui.h: 没有那个文件或目录
 #include "imgui.h"
          ^~~~~~~~~
compilation terminated.
app/GraphSLAM/CMakeFiles/exe_GraphSLAM.dir/build.make:75: recipe for target 'app/GraphSLAM/CMakeFiles/exe_GraphSLAM.dir/main.cc.o' failed
make[2]: *** [app/GraphSLAM/CMakeFiles/exe_GraphSLAM.dir/main.cc.o] Error 1
CMakeFiles/Makefile2:201: recipe for target 'app/GraphSLAM/CMakeFiles/exe_GraphSLAM.dir/all' failed
make[1]: *** [app/GraphSLAM/CMakeFiles/exe_GraphSLAM.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
```

I've tried to solve this by manually linking `imgui` from [https://github.com/ocornut/imgui](https://github.com/ocornut/imgui) in `CMakeLists.txt` and other errors occurred.

Did I miss something?

**Comment by PericlesHat** [comment]
I've solved this with `-DBUILD_GUI=ON`. My device cannot compile the project in a version without GUI.

**Comment by dhxxoo** [comment]
> 
Hi, i met the same problem here, could you please tell me how to deal with it more specifically?

**Comment by PericlesHat** [comment]
> > 
> 
> Hi, i met the same problem here, could you please tell me how to deal with it more specifically?

I solved this using `cmake -DBUILD_GUI=ON ..`.

**Comment by dhxxoo** [comment]
> 

thank you so much! it worked for me when i using `cmake -DBUILD_GRAPHPRED=ON -DBUILD_GUI=ON ..`. I guess maybe it is the network problems when cloning something.
