### ISSUE TITLE
Bug related to ProjectInseg

### ISSUE THREAD

**Issue by SgtVincent** [ShunChengWu/SceneGraphFusion#3]
Hi! 

I am following the data preparation pipeline in [3DSSG](https://github.com/ShunChengWu/3DSSG/tree/master/data_processing), to generate estimated segment map file `inseg.ply` on 3RScan dataset. 

When executing command 

> ./bin/exe_GraphSLAM --pth_in ./data/3RScan/754e884c-ea24-2175-8b34-cead19d4198d/sequence --pth_out ./data/3RScan/754e884c-ea24-2175-8b34-cead19d4198d --save_name inseg.ply  --rendered 0 --min_pyr_level 2 --depth_edge_threshold 0.98 --save 1 --save_graph 1 --save_graph_ply 0 --save_surfel_ply 1 --save_time 0 --binary 1

called by https://github.com/ShunChengWu/3DSSG/blob/24d4ac520c3441fb6815d0d4890dd845e10e5cc7/script/RUN_GenSeg.py#L35

I got the `segmentation fault (core dumped)` from method `inseg_->ProcessFrame(depthImage, colorImage);` on line 74 in file ./libGraphSLAM/GraphSLAM.cpp
https://github.com/ShunChengWu/SceneGraphFusion/blob/4c632d12dd492c362ee2708a85410f367724b572/libGraphSLAM/GraphSLAM.cpp#L74

I tried to step into this method, but this function is linked from the pre-compiled static library ./lib/libInSegLib_linux.a. Source code seems not public. 

After several tries, I found that the error disappeared after removing flag "--rendered 0".

I wonder if this option affects the final output file `inseg.ply`. Besides, just curious, what could cause this error?

**Comment by SgtVincent** [comment]
Update: 
If flag `--rendered` is set to 0, the loaded `depthImage` has a shape of (224, 172) while `colorImage` has a shape of (540, 960). If flag `--rendered` is set to 1, `depthImage` will be reshaped to (540, 960) by the reindeer before being sent to `inseg_->ProcessFrame()` method. I wonder if this mismatch of sizes could lead to segmentation fault.

**Comment by ShunChengWu** [comment]
Hi, 
The image sizes are correct for 3RScan dataset. We currently only support with rendered view. 
If you want to use the original depth image you will need to resize it to be the same size as the RGB image. But we don't encourage that since the depth maps from 3RScan dataset are kind of bad.

**Comment by SgtVincent** [comment]
Thanks for your answer! Yet it really confused me that you assert `dataset == 'ScanNet'` in RUN_GenSeg.py script. I thought you would ONLY use non-rendered mode for 3RScan dataset. See https://github.com/ShunChengWu/3DSSG/blob/24d4ac520c3441fb6815d0d4890dd845e10e5cc7/script/RUN_GenSeg.py#L113

**Comment by ShunChengWu** [comment]
previously the program didn't support the online generation of the rendered view of 3RScan. So you would need to generate the rendered view first then run our code. We added this feature later but forgot to change that part in the script. the rendered view should always be true unless you want to train with your own settings. I will change that soon. 
Thanks

**Comment by SgtVincent** [comment]
Problem solved, thanks!
