### ISSUE TITLE
If this can be used to generate scene graph with a complete indoor model rather than rgb-d sequence?

### ISSUE THREAD

**Issue by dhxxoo** [ShunChengWu/SceneGraphFusion#30]
### 
![image](https://github.com/ShunChengWu/SceneGraphFusion/assets/109494078/3864a375-5dc0-4395-867e-d334eb62c325)
output like this.

**Comment by dhxxoo** [comment]
Thanks for this great work！

**Comment by ShunChengWu** [comment]
Please check out my 3DSSG repo (https://github.com/ShunChengWu/3DSSG)
You will need to change the input scene to the same format as provided by 3RScan dataset or the segment map ply files generated by this repo

**Comment by dhxxoo** [comment]
> Please check out my 3DSSG repo (https://github.com/ShunChengWu/3DSSG) You will need to change the input scene to the same format as provided by 3RScan dataset or the segment map ply files generated by this repo

Really appreciate for you answering! So with the right format of scene, how can i load the scene to GraphSlam_GUI?

**Comment by ShunChengWu** [comment]
hm... You can't. The GUI only supports image sequences for now. 
A load function still needs to be implemented. I have that in my other version of code but do not have time to do that yet. 
If someone else is interested in implementing this function please feel free to create a pull request. 
I will mark this on my todo list.
