### ISSUE TITLE
如何在RGB-D数据流中使用

### ISSUE THREAD

**Issue by Geralt-of-winterfall** [ShunChengWu/SceneGraphFusion#32]
作者您好，对于您的代码有部分问题想要请教。
关于语义分割的实现部分仅提供了接口部分，实现封装在libInSegLib_linux.a。
对于RGB-D数据流，通过SLAM可以获得单帧位姿，通过语义分割可以获得单帧的分割结果。
如果要处理RGB-D数据流，现有代码在部分实现不清楚的情况下，能否实现这个功能，主要是需要修改那部分内容？

**Comment by ShunChengWu** [comment]
This method takes RGB-D as the input. However, it uses rendered depth in this implementation. 
If you want to use a real depth maps, you will need to implement a dataloader yourself.
