### ISSUE TITLE
Please......

### ISSUE THREAD

**Issue by qorgh346** [ShunChengWu/SceneGraphFusion#6]
Hello, I am a student studying in South Korea.

The following things were installed. that  --> { Prerequisites,OpenCV, Eigen,Assimp,With GUI: , BUILD ( cmake -DBUILD_GUI=ON ..) }
I contacted you because there was an error in the process of executing the code.

My environment is ubuntu 18.04.5.

When I set BUILD_GRAPHPERED=ON when I set up cmake, there was an error that the onnxruntime library could not be found, so I set up -DBUILD_GUI=ON and ran cmake.

Next, I performed.
1. git clone git@github.com:WaldJohannaU/3RScan.git 
2. cd 3RSan
3. bash setup.sh
4. ./exe_GraphSLAM --pth_in /3RScan/data/3RScan/4acaebcc-6c10-2a2a-858b-29c7e4fb410d/sequence/

Error : 
(hobe) ailab@ailab:~/Desktop/hobe/SceneGraphFusion/bin$ ./exe_GraphSLAM --pth_in ../data/3RScan/4acaebcc-6c10-2a2a-858b-29c7e4fb410d/sequence/
I0910 14:59:18.666 main.cc:main:154] Buliding data loader...
detect data type: 3RScanterminate called after throwing an instance of 'std::runtime_error'
  what():  unable to open _info file
Aborted (core dumped)

An error has occurred.
I'd appreciate it if you could help me.

Please contact qorgh346@naver.com ....
Thank you

**Comment by ShunChengWu** [comment]
The system cannot find the _info file, which was provided from each 3RScan sequence. 
Please check if the input data path is set correctly, and also if the `sequence.zip` is unzipped. 

The _info.txt file should locate at 
`[3RScan]/[sequence_id]/sequence/_info.txt`

**Comment by qorgh346** [comment]
Oh.. The Path is wrong... Thank you.


Is there an error?

**I0911 12:51:41.316 main.cc:main:154] Buliding data loader...
detect data type: 3RScanI0911 12:51:41.511 main.cc:main:166] Building renderer...
libEGL warning: DRI2: failed to authenticate
I0911 12:51:44.245 main.cc:main:174] Building framework...
I0911 12:51:44.246 main.cc:main:211] start processing frames...
V0911 12:51:44.250 main.cc:main:214] process frame: 1
V0911 12:51:44.352 main.cc:main:214] process frame: 2
V0911 12:51:44.444 main.cc:main:214] process frame: 3
V0911 12:51:44.533 main.cc:main:214] process frame: 4
V0911 12:51:44.623 main.cc:main:214] process frame: 5
V0911 12:51:44.722 main.cc:main:214] process frame: 6
V0911 12:51:44.820 main.cc:main:214] process frame: 7
V0911 12:51:44.920 main.cc:main:214] process frame: 8
V0911 12:51:45.020 main.cc:main:214] process frame: 9
V0911 12:51:45.119 main.cc:main:214] process frame: 10
V0911 12:51:45.221 main.cc:main:214] process frame: 11
V0911 12:51:45.327 main.cc:main:214] process frame: 12
V0911 12:51:45.433 main.cc:main:214] process frame: 13
V0911 12:51:45.536 main.cc:main:214] process frame: 14
V0911 12:51:45.639 main.cc:main:214] process frame: 15
V0911 12:51:45.737 main.cc:main:214] process frame: 16
V0911 12:51:45.830 main.cc:main:214] process frame: 17
V0911 12:51:45.916 main.cc:main:214] process frame: 18
V0911 12:51:45.998 main.cc:main:214] process frame: 19
V0911 12:51:46.080 main.cc:main:214] process frame: 20
V0911 12:51:46.164 main.cc:main:214] process frame: 21
V0911 12:51:46.252 main.cc:main:214] process frame: 22
V0911 12:51:46.342 main.cc:main:214] process frame: 23
V0911 12:51:46.429 main.cc:main:214] process frame: 24
V0911 12:51:46.513 main.cc:main:214] process frame: 25
V0911 12:51:46.600 main.cc:main:214] process frame: 26
V0911 12:51:46.687 main.cc:main:214] process frame: 27
V0911 12:51:46.774 main.cc:main:214] process frame: 28
V0911 12:51:46.860 main.cc:main:214] process frame: 29
V0911 12:51:46.950 main.cc:main:214] process frame: 30
V0911 12:51:47.038 main.cc:main:214] process frame: 31
V0911 12:51:47.126 main.cc:main:214] process frame: 32
V0911 12:51:47.214 main.cc:main:214] process frame: 33
V0911 12:51:47.303 main.cc:main:214] process frame: 34
V0911 12:51:47.391 main.cc:main:214] process frame: 35
V0911 12:51:47.483 main.cc:main:214] process frame: 36
V0911 12:51:47.575 main.cc:main:214] process frame: 37
V0911 12:51:47.667 main.cc:main:214] process frame: 38
V0911 12:51:47.758 main.cc:main:214] process frame: 39
V0911 12:51:47.848 main.cc:main:214] process frame: 40
V0911 12:51:47.940 main.cc:main:214] process frame: 41
V0911 12:51:48.035 main.cc:main:214] process frame: 42
V0911 12:51:48.128 main.cc:main:214] process frame: 43
V0911 12:51:48.218 main.cc:main:214] process frame: 44
V0911 12:51:48.307 main.cc:main:214] process frame: 45
V0911 12:51:48.401 main.cc:main:214] process frame: 46
V0911 12:51:48.496 main.cc:main:214] process frame: 47
V0911 12:51:48.597 main.cc:main:214] process frame: 48
V0911 12:51:48.701 main.cc:main:214] process frame: 49
V0911 12:51:48.806 main.cc:main:214] process frame: 50
V0911 12:51:48.922 main.cc:main:214] process frame: 51
V0911 12:51:49.032 dataloader_3rscan.cpp:Retrieve:123] Cannot find path:
../3RScan/data/3RScan/4acaebcc-6c10-2a2a-858b-29c7e4fb410d/sequence//frame-000051.depth.pgm
../3RScan/data/3RScan/4acaebcc-6c10-2a2a-858b-29c7e4fb410d/sequence//frame-000051.color.jpg
I0911 12:51:49.032 main.cc:main:232] frame processing finished.
I0911 12:51:49.032 main.cc:main:237] saving results.
I0911 12:51:49.233 EvaluationHelper.h:printResultToFile:104] Runtime saved to .//times.txt**



Where can I check the results? ㅠㅠ

**Comment by ShunChengWu** [comment]
Please check:
https://github.com/ShunChengWu/SceneGraphFusion/blob/69f500a148df934b36155e46a5fa636a94d5916a/app/GraphSLAM/main.cc#L76-L80

**Comment by ShunChengWu** [comment]
close due to inactivity.

**Comment by zhangzjjjjjj** [comment]
@qorgh346 @ShunChengWu Sorry to bother you, but I've run inference on the test sequence (4acaebcc-6c10-2a2a-858b-29c7e4fb410d) and obtained the results. However, when I checked the `predictions.json` file, it was empty, like this.
```
{
   "4acaebcc-6c10-2a2a-858b-29c7e4fb410d": {
       "edges": {

           },
       "kfs": {

           },
       "nodes": {

           }
       }
   }
```
"The same issue occurs with the predictions.json file on another sequence (754e884c-ea24-2175-8b34-cead19d4198d) of the example dataset. Meanwhile, the other two results, `inseg.ply` and `node_semantic.ply`, are correctly populated. Therefore, my question is: is the output of predictions.json normal?"
