### ISSUE TITLE
请问怎么构建自己的数据加载器？只需要RGB-D + Pose输入

### ISSUE THREAD

**Issue by why-freedom** [ShunChengWu/SceneGraphFusion#7]
## 并且，设置use_render = false，程序运行报错

 ./exe_GraphSLAM --pth_in ../data/3RScan/754e884c-ea24-2175-8b34-cead19d4198d/sequence/
I0915 00:34:21.290 main.cc:main:155] Buliding data loader...
detect data type: 3RScanI0915 00:34:21.462 main.cc:main:175] Building framework...
I0915 00:34:21.469 main.cc:main:212] start processing frames...
V0915 00:34:21.472 main.cc:main:215] process frame: 1
V0915 00:34:21.476 main.cc:main:215] process frame: 2
Segmentation fault (core dumped)

**Comment by ShunChengWu** [comment]
The code we provided only support using rendered view when you use the 3RScan input. 
It is easy to write your own data loader by inheriting `DatasetLoader_base` in https://github.com/ShunChengWu/SceneGraphFusion/blob/main/libDataLoader/include/dataLoader/dataset_loader.h

**Comment by why-freedom** [comment]
Thank you for your reply. If I write my own data loader, can I choose not to use render? Just use RGBD+Pose directly and output the scene graph？

> The code we provided only support using rendered view when you use the 3RScan input.
> It is easy to write your own data loader by inheriting `DatasetLoader_base` in https://github.com/ShunChengWu/SceneGraphFusion/blob/main/libDataLoader/include/dataLoader/dataset_loader.h

**Comment by why-freedom** [comment]
Why do I run ScanNet and not show labels like your video (open RELATIONSHIP), but only node pairs (open NEIGHBOR)?

**Comment by ShunChengWu** [comment]
1:
sure. renderer only supports ScanNet and 3RScan. 

2:
it seems like the prediction backend was not run correctly.

**Comment by why-freedom** [comment]
## Thank you for your reply very much！
### 1、When I cmake -DBUILD_GRAPHPRED=ON -DBUILD_GUI=ON ..
, here is an error:

**Comment by jkabalar** [comment]
Hello, I can confirm it works following this steps:
`git clone --recursive https://github.com/microsoft/onnxruntime/tree/v1.8.2
cd onnxruntime
./build.sh --config RelWithDebInfo --build_shared_lib --parallel
cd build/Linux/RelWithDebInfo
sudo make install`
Can you try whether that works for you?

**Comment by why-freedom** [comment]
> Hello, I can confirm it works following this steps:
> 
> ```
> git clone --recursive https://github.com/microsoft/onnxruntime/tree/v1.8.2
> cd onnxruntime
> ./build.sh --config RelWithDebInfo --build_shared_lib --parallel
> cd build/Linux/RelWithDebInfo
> sudo make install
> ```
> 
> Can you try whether that works for you?

That works, Thank you very much!

**Comment by why-freedom** [comment]
## This is New error，when i run:
why@why:~/Documents/SceneGraph/SceneGraphFusion/bin$ ./exe_GraphSLAM_GUI --pth_in /home/why/Documents/SceneGraph/DataSet/scans/scene0000_00/scene0000_00.sens -pth_model ../data/model/traced/
I0916 10:20:11.939 main.cc:main:155] Buliding data loader...
inputeType is 0
detect data type: ScanNet
I0916 10:20:13.109 main.cc:main:179] Building framework...
I0916 10:20:13.109 main.cc:main:214] start gui...
W0916 10:20:26.111 GraphSLAM.cpp:RunFullPrediction:136] predictor is not initialized!
W0916 10:20:27.020 GraphSLAM.cpp:RunFullPrediction:136] predictor is not initialized!
V0916 10:20:27.098 graph.cpp:Merge:58] Merge segment 1 and 90
V0916 10:20:27.098 graph.cpp:Merge:61] remove surfels
V0916 10:20:27.099 graph.cpp:Merge:90] remove edges
V0916 10:20:27.099 graph.cpp:Merge:123] copy prediction
V0916 10:20:27.207 graph.cpp:Merge:49] Cannot find node 90 to merge
V0916 10:20:27.313 graph.cpp:Merge:49] Cannot find node 90 to merge

**Comment by ShunChengWu** [comment]
close cuz solved

**Comment by Bovey0809** [comment]
> ## Thank you for your reply.
> ## 1、If I write my own data loader, can I choose not to use render? Just use RGBD+Pose directly and output the scene graph？
> ## 2、Why do I run ScanNet and not show labels like your video (open RELATIONSHIP), but only node pairs (open NEIGHBOR)?And I click “Save Graph”， it does not work，as:
> { "scene0000_00": { "edges": {
> 
> ```
>        },
>    "kfs": {
> 
>        },
>    "nodes": {
> 
>        }
>    }
> ```
> 
> }

Could you please provide the code for your new dataloader, I'm struggling to modify the code for the same usage.
input: rgbd+pose, instead of rgbd+pose+render

**Comment by BIT-TYJ** [comment]
> > ## Thank you for your reply.
> > ## 1、If I write my own data loader, can I choose not to use render? Just use RGBD+Pose directly and output the scene graph？
> > ## 2、Why do I run ScanNet and not show labels like your video (open RELATIONSHIP), but only node pairs (open NEIGHBOR)?And I click “Save Graph”， it does not work，as:
> > { "scene0000_00": { "edges": {
> > ```
> >        },
> >    "kfs": {
> > 
> >        },
> >    "nodes": {
> > 
> >        }
> >    }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> 
> Could you please provide the code for your new dataloader, I'm struggling to modify the code for the same usage. input: rgbd+pose, instead of rgbd+pose+render

Hello, could you please provide the code for your new dataloader? I want to run on custom images.  Thank you very much!
