### ISSUE TITLE
Content of [labels.instances.annotated.v2.ply], [mesh.refined.v2.obj] and [semseg.v2.json]

### ISSUE THREAD

**Issue by PNeigel** [ShunChengWu/SceneGraphFusion#9]
Would you be so kind to help me out what exactly is stored in these files and what they are used for?

First is a mesh where vertices are annotated with rgb, "objectID", "globalID", NYU40, Eigen13, RIO27.

Is this information necessarily required? As far as I understand the segmentation should happen only from the depth images & incrementally created global vertex map in accordance to [K. Tateno 2015].

Second file seems to also be a mesh, where is it needed?

Third file is semantic segmentation of point cloud clusters/objects? Is this file needed? As far as I understand graph NN takes (non-semantically) segmented input point cloud clusters and outputs a graph, so semantic segmentation shouldn't be necessary I believe.

Thanks in advance.

**Comment by ShunChengWu** [comment]
The system only needs the mesh file to generate a rendered views. 

The files you mentioned are from the 3RScan dataset. You can find the detailed explanation on those files there
https://github.com/WaldJohannaU/3RScan
